version: '3'

services:

  academia-mysql:
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=academia
      - MYSQL_DATABASE=academia
      - MYSQL_USER=academia
      - MYSQL_PASSWORD=academia
    volumes:
      - academia-mysql-data:/var/lib/mysql

  academia-api:
    build:
      context: ./academia-api
      dockerfile: scripts/Dockerfile
    depends_on:
      - academia-mysql
    ports:
      - "8080:8080"
    volumes:
      - academia-maven:/root/.m2

  academia-client-web:
    build:
      context: ./academia-client-web
      dockerfile: scripts/Dockerfile-prod
    depends_on:
      - academia-api
    ports:
      - "3000:80"

volumes:
  academia-maven:
  academia-mysql-data:
