package academia.hello;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
//    @Autowired // This means to get the bean called accountRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private AccountRepository accountRepository;
//
//    @GetMapping(path="/add") // Map ONLY GET Requests
//    public @ResponseBody String addNewUser (@RequestParam String name
//            , @RequestParam String email) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//
//        Account n = new Account(name, email, new ArrayList<>());
////        n.setName(name);
////        n.setEmail(email);
//        accountRepository.save(n);
//        return "Saved";
//    }
//
//    @GetMapping(path="/all")
//    public @ResponseBody Iterable<Account> getAllUsers() {
//        // This returns a JSON or XML with the users
//        return accountRepository.findAll();
//    }
}