# build environment
FROM node:8.11.1-alpine as builder

WORKDIR /app

# copia definições de dependências
COPY package*.json ./
COPY yarn.lock ./

# instala dependências
RUN yarn

COPY . .

RUN yarn build

# production environment
FROM nginx:1.11.10-alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY scripts/nginx/nginx.conf /etc/nginx/
COPY scripts/nginx/default.conf /etc/nginx/conf.d
